package com.kitcenter.app.homework.lesson15EnumerationGenerics;

public enum AllTasks {
    PRIMITIVECONVERTER, ALLMATHFUNCS, ARRAYTASK1EVEN, ARRAYTASK2ODD, ARRAYTASK3RANDOM,
    ARRAYTASK4RANDOMBIG, ARRAYTASK5D2, ARRAYTASK6D2ALIGNMENT, TASK7SUMACCUMULATION, PALINDROMEORNOT,
    PALINDROMESENTENCEORNOT, HUMAN, WHITECOLLAR, BICYCLEWITHRINGANDCUSTOM, BOUQUET, FOOTBALLCLUB, HOUSE,
    TRACTOR, EXIT
}
